- name: install apache and php for Ubuntu servers
  tags: appache,apache2,ubuntu
  package:
    name:
    - "{{ apache_package_name }}"
    - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Ubuntu" 
    
- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: testfile.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
     
- name: add rules to firewall and bring it up
  tags: ufw,firewall
  ufw:
    rule: allow
    name: apache
  register: ufw

- name: restart ufw 
  tags: ufw,firewall
  ufw:
    state: reloaded
  when: ufw.changed    
      