---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    
- hosts: all
  become: true
  tasks:
  
  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root
 
  - name: add ssh key for simone
    tags: alaways
    authorized_key:
       user: simone
       key: ""
  - name: add sudoers file for simone
    tags: always
    copy:
       src: sudoer_simone
       dest: /etc/sudoers.d/simone
       owner: root
       group: root
       mode: 0440

