---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    
- hosts: all
  become: true
  tasks:
  
  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root
 
  - name: add ssh key for simone
    tags: alaways
    authorized_key:
       user: simone
       key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC74011kgm0VA3Mt1KJUPBTx0umGlUYBV+hlb5p0xbX2s5BLzV3IBWVJ/em59zAbdBk4xe2ji7HamASQo9Xu9QhF0pQdU1ud+mCXG/vrs1vl03KvQ52TtDLqWl7L4qezpi7RUc3nL4aEGkFicm4JOhFT7wygNcyir3ncirlm14fpDSoGTer5iHC/p/KUNiZWpHFPAQOeCtY1sRvMuk8l60/eXi4HAam66Isl+Uf0UuyspBMHegBfIJFSjtWBO8nESlnvdQ1gnx9SI+qT+LUjITphnWtzFTrBMAb3hleHoCu6hz0u4Qw2OdAK5FL3COZsczUEHsvN5ds9lMVcZKGf9WrifVGKuLvHFd0DDw0ZBG4fwTCh7DJo7sisgc3wTdQ3NcTVNhCb5HIUDWbcAFAcls50S7AmzoeCMvsfj3zFpsI3ZGD2BjTDxjW2aVm9sDuGFif5rrEv7Swf/5y6oa65u2Mj/GklXDlyRJUvT8QGNKpXAauwWAk5ATUC0N8yz7tZYE= neon@neon-VS"
      
  - name: add sudoers file for simone
    tags: always
    copy:
       src: sudoer_simone
       dest: /etc/sudoers.d/simone
       owner: root
       group: root
       mode: 0440

